apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echo
  name: echo
spec:
  containers:
  - image: mendhak/http-https-echo
    name: echo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
